class AlreadyNoticedException(Exception):
  pass

class OutOfTimeException(Exception):
  pass